roles = [
    "software engineer",
    "software developer",
    "backend developer",
    "frontend developer",
    "full stack developer",
    "python developer",
    "java developer",
    "golang developer",
    "react developer",
    "node.js developer",
    "devops engineer",
    "cloud engineer",
    "site reliability engineer",
    "data scientist",
    "data analyst",
    "data engineer",
    "machine learning engineer",
    "AI engineer",
    "business analyst",
    "QA engineer",
    "automation test engineer",
    "mobile app developer",
]

locations = {
    "in": [
        "bangalore",
        "hyderabad",
        "pune",
        "mumbai",
        "chennai",
        "gurgaon",
        "noida",
        "delhi",
        "kolkata",
        "ahmedabad",
        "kochi",
    ],
    "us": [
        "new york",
        "san francisco",
        "seattle",
        "austin",
        "boston",
        "chicago",
        "los angeles",
        "dallas",
        "atlanta",
        "remote usa",
    ],
    "sg": [
        "singapore",
    ],
    "ae": [
        "dubai",
        "abu dhabi",
        "sharjah",
    ],
}